- .gitignore
- src/NHSD.BuyingCatalogue.API/Extensions/ServiceCollectionExtensions.cs
- src/NHSD.BuyingCatalogue.API/NHSD.BuyingCatalogue.API.csproj
- src/NHSD.BuyingCatalogue.API/Startup.cs
- src/NHSD.BuyingCatalogue.Application/Infrastructure/Mapping/AutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.Application/NHSD.BuyingCatalogue.Application.csproj
- src/NHSD.BuyingCatalogue.Application/Solutions/Queries/GetAllSolutionSummaries/GetAllSolutionSummariesQueryHandler.cs
- tests/NHSD.BuyingCatalogue.Application.Tests/Infrastructure/AutoMapperFactory.cs
- tests/NHSD.BuyingCatalogue.Application.Tests/NHSD.BuyingCatalogue.Application.Tests.csproj
- tests/NHSD.BuyingCatalogue.Application.Tests/Solutions/Queries/GetAllSolutionSummariesQueryHandlerTests.cs
This was to simplify the code to map from a domain model object to a view model object.
> Task 2804 - Introduced AutoMapper

- src/NHSD.BuyingCatalogue.API/Controllers/CapabilitiesController.cs
- src/NHSD.BuyingCatalogue.API/Extensions/ServiceCollectionExtensions.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/HealthChecks/HealthCheckTags.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/HealthChecks/PersistenceLayerHealthCheck.cs
- src/NHSD.BuyingCatalogue.API/NHSD.BuyingCatalogue.API.csproj
- src/NHSD.BuyingCatalogue.API/Startup.cs
- src/NHSD.BuyingCatalogue.Application/Infrastructure/HealthChecks/IRepositoryHealthCheck.cs
- src/NHSD.BuyingCatalogue.Persistence/HealthChecks/RepositoryHealthCheck.cs
- src/NHSD.BuyingCatalogue.Persistence/Infrastructure/DbConnectionFactory.cs
- src/NHSD.BuyingCatalogue.Persistence/Infrastructure/IDbConnectionFactory.cs
- src/NHSD.BuyingCatalogue.Persistence/NHSD.BuyingCatalogue.Persistence.csproj
This will allow any integration tests to verify the status of the application before executing any tests.
It will also allow monitoring products to determine the ready status of the application.
> Task 2984 - Added health check endpoints

- src/NHSD.BuyingCatalogue.Application/Infrastructure/Mapping/AutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.Application/Solutions/Commands/UpdateSolution/UpdateSolutionViewModel.cs
- src/NHSD.BuyingCatalogue.Application/Solutions/Queries/GetSolutionById/SolutionByIdViewModel.cs
- tests/NHSD.BuyingCatalogue.Application.UnitTests/Solutions/Commands/UpdateSolutionHandlerTests.cs
This is to help the Front-end consume this information easier.
> Task 3013 - Change the data type of the Solution marketing data

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/BrowserBased/BrowserBasedController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/NativeMobile/NativeMobileController.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/BrowserBased/Display Sub-Form Browser Based Client Type.2782.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeMobile/Display Sub-Form Native Mobile Client Type.3604.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSectionsSteps.cs
> 4075 rename subdashboard urls from sections to

- Launch Environment.ps1
- README.md
- Run Code Coverage.ps1
- Tear Down Environment.ps1
- launch_environment.sh
- tear_down_environment.sh
- clean OpenCover directory before we generate code coverage reports
- added `-q` flag to the scripts - this way we don't do a `docker ps` 
- updated & reformatted readme
> Code coverage improvements

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/NativeDesktop/NativeDesktopConnectivityDetailsController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/GetNativeDesktopConnectivityDetails.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/GetNativeDesktopConnectivityDetailsResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/UpdateNativeDesktopConnectivityDetailsViewModel.cs
> 3619: Canned Data. Native Desktop Connectivity

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/NativeDesktop/NativeDesktopController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/NativeDesktopResult.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/Display Sub-Form Native Desktop Client Type.3614.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSectionsSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NativeDesktop/NativeDesktopControllerTests.cs
Let equity be the rule of our actions
> 3622 Implemented Dashboard for Native Desktop Hardware Requirements

- src/NHSD.BuyingCatalogue.Solutions.API/IClientApplicationNativeMobileExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeMobile/NativeMobileResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/SolutionDashboardResult.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Dashboard/Display Marketing Page Dashboard Client Application Types Section.2724.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/ClientApplicationTypes/NativeMobileSectionSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetDashboardTests.cs
Ants can carry objects 50 times their own body weight in their jaws. Relative to their size, their muscles are thicker than those of larger animals - even humans. This ratio enables them to produce more force and carry larger objects. If you had muscles in the proportions of ants, you'd be able to heave a Hyundai over your head!
> 3612: Implemented summing logic for NativeMobile

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/NativeDesktop/NativeDesktopMemoryAndStorageController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/GetNativeDesktopMemoryAndStorageResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/NativeDesktop/NativeDesktopMemoryAndStorage.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Mapping/SolutionAutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSolutionById/NativeDesktopMemoryAndStorageDto.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/NativeDesktopMemoryAndStorage/Supplier Get Native Desktop Memory And Storage.3620.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSectionsSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NativeDesktop/NativeDesktopMemoryAndStorageControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/GetClientApplicationBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionAutoMapperProfileTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionGetByIdTests.cs
Ant plants, or myrmecophytes, are plants that have naturally occurring hollows in which ants can take shelter or feed. These cavities may be hollow thorns, stems, or even leaf petioles. The ants live in the hollows, feeding on sugary plant secretions or the excretions of sap-sucking insects. What does a plant get for providing such luxurious accommodations? The ants defend the host plant from herbivorous mammals and insects and may even prune away parasitic plants that attempt to grow on it.
> 3620: Implemented Native Desktop Memory And Storage GET

- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/NativeDesktopResult.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/Display Sub-Form Native Desktop Client Type.3614.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSectionsSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NativeDesktop/NativeDesktopControllerTests.cs
Two-thirds of an octopus’ neurons reside in its arms, not its head. As a result, the arms can problem solve how to open a shellfish while their owners are busy doing something else, like checking out a cave for more edible goodies. The arms can even react after they’ve been completely severed. In one experiment, severed arms jerked away in pain when researchers pinched them.
> 3620: Implemented Native Desktop Memory and Storage Dashboard

- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/NativeDesktop/NativeDesktopMemoryAndStorageSection.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/NativeDesktop/NativeDesktopMemoryAndStorageSectionAnswers.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/NativeDesktop/NativeDesktopSubSections.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Preview/Display Marketing Page Preview Native Desktop Section.3622.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/ClientApplicationTypes/NativeDesktopSectionSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPreviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPublicTests.cs
Mating and parenthood are brief affairs for octopuses, who die shortly after. The species practices external fertilization. Multiple males either insert their spermatophores directly into a tubular funnel that the female uses to breathe, or else literally hand her the sperm, which she always accepts with one of her right arm (researchers do not know why). Afterwards, males wander off to die. As for the females, they can lay up to 400,000 eggs, which they obsessively guard and tend to. Prioritizing their motherly duties, females stop eating. But she doesn’t starve to death–rather, when the eggs hatch, the female’s body turns on her. Her body undertakes a cascade of cellular suicide, starting from the optic glands and rippling outward through her tissues and organs until she dies.
> 3620 Implemented Public/Preview for Native Desktop Memory and Storage

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/NativeDesktop/NativeDesktopAdditionalInformationController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/UpdateNativeDesktopAdditionalInformationViewModel.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/NativeDesktop/UpdateNativeDesktopAdditionalInformation/UpdateNativeDesktopAdditionalInformationCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/NativeDesktop/UpdateNativeDesktopAdditionalInformation/UpdateNativeDesktopAdditionalInformationExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/NativeDesktop/UpdateNativeDesktopAdditionalInformation/UpdateNativeDesktopAdditionalInformationHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/NativeDesktop/UpdateNativeDesktopAdditionalInformation/UpdateNativeDesktopAdditionalInformationValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/ServiceCollectionExtensions.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/NativeDesktopAdditionalInformation/Supplier Edit NativeDesktopAdditionalInformation Validation.3623.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/NativeDesktopAdditionalInformation/Supplier Edit NativeDesktopAdditionalInformation.3623.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/NativeDesktopAdditionalInformation/Supplier Get NativeDesktopAdditionalInformation.3623.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/EditSectionPutSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NativeDesktop/NativeDesktopAdditionalInformationControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/NativeDesktop/SolutionUpdateNativeDesktopConnectivityDetailsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/NativeDesktop/UpdateNativeDesktopAdditionalInformationTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/TestContext.cs
Implemented the endpoint and all tests
> 3623: Native desktop additional information PUT

- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/NativeDesktop/NativeDesktopResult.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/NativeDesktop/Display Sub-Form Native Desktop Client Type.3614.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSectionsSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NativeDesktop/NativeDesktopControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetDashboardTests.cs
Implemented Dashboard and associated tests
> 3623: Native desktop additional information dashboard

- tests/NHSD.BuyingCatalogue.API.IntegrationTests/NHSD.BuyingCatalogue.API.IntegrationTests.csproj
- tests/NHSD.BuyingCatalogue.API.UnitTests/NHSD.BuyingCatalogue.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Data.Tests/NHSD.BuyingCatalogue.Data.Tests.csproj
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/NHSD.BuyingCatalogue.Infrastructure.Tests.csproj
- tests/NHSD.BuyingCatalogue.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NHSD.BuyingCatalogue.Solutions.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests.csproj
Tests are not getting discovered in Rider on a Mac.
Reference to the bug report.
https://youtrack.jetbrains.com/issue/RIDER-37769
> 4415: Rollback NUnit nuget package

- azure-pipelines.yml
Appears I didn't realise the two jobs now run on different machines, and the later docker build task relies on the /out folder created during the earlier .net build and publish tasks.
I've now added build and publish tasks to the docker push job and that appears to enable the docker build to work
> 4309-PR-Check-Part2

- src/NHSD.BuyingCatalogue.SolutionLists.API/SolutionListController.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/ListSolutionsFilterViewModel.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/ListSolutionsResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionCapabilityResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionSummaryResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionSupplierResult.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/SolutionListControllerTests.cs
and start exposing appropriate 'Results' instead
> 5120: Refactored the POST endpoint to stop exposing the 'SolutionListDto'

- README.md
[AB#6912](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6912)
> Remove DataModel repo link from the readme

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/Suppliers/SolutionSupplierController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/Suppliers/SuppliersController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Suppliers/GetSolutionSupplierResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Suppliers/GetSuppliersNameResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Suppliers/GetSuppliersResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Suppliers/UpdateSolutionSupplierViewModel.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSuppliers/UpdateSolutionSupplierCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSuppliers/UpdateSupplierExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSuppliers/UpdateSupplierHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSuppliers/UpdateSupplierValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/ServiceCollectionExtensions.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Suppliers/SolutionSupplierControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/UpdateSupplierTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/TestContext.cs
Story; AB#4830
Task: [AB#7173](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7173)
> 4830: Supplier get canned data

- charts/bapi-db-deploy/templates/job.yaml
- charts/bapi-db-deploy/values.yaml
- src/NHSD.BuyingCatalogue.Database.Deployment/entrypoint.sh
Story: [AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
Task: [AB#7034](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7034)
Change prompted from this [discussion](https://github.com/nhs-digital-gp-it-futures/platform-helm/pull/14#discussion_r435029758).
> Add configurable port variable to dacpac apply

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/PricingController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/ItemUnitResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/PricesResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/PricingResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/TierResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/TimeUnitResult.cs
Story: [AB#7260](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7260)
Task: [AB#7516](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7516)
> 7260: Pricing GET Canned Data

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/PricingController.cs
Story: [AB#7260](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7260)
Task: [AB#7516](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7516)
> 7260: Canned data fix

- src/NHSD.BuyingCatalogue.SolutionLists.API/SolutionListController.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/ListSolutionsFilterViewModel.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Persistence/SolutionListReader.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/ListSolutionsHandler.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/IListSolutionsQueryData.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/Persistence/ISolutionListRepository.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Persistence/Repositories/SolutionListRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/SolutionList/No selection criteria browse.2053.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Solution/ListSolutionsSteps.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/SolutionListControllerTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/SolutionListTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/SolutionListRepositoryTests.cs
Story: [AB#5350](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5350)
Task: [AB#7482](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7482)
> 5350: SupplierID filter get list

- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SupplierRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Supplier/Supplier Search.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Suppliers/ListSupplierSteps.cs
Bug: [AB#7410](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7410)
Task: [AB#7484](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7484)
> Feature bug 7410 wildcards in supplier search

- charts/bapi-db-deploy/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7663](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7663)
> Change job's name to allow re-deployments

- charts/bapi-db-deploy/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7663](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7663)
> Remove release revision to only trigger on version change

- charts/bapi-db-deploy/templates/_helpers.tpl
- charts/bapi/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7440)
> Use local repository even when useLocalImage=false

- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Delete any existing associated data on migration

- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Truncate old solution table on migration

- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Drop purchasing model table on pre-deploy

- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Drop purchasing model table before DELETE

- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Drop original schema pricing tables on pre-deploy

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/PricingController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/PriceResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Pricing/PricingResult.cs
Story: [AB#7840](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7840)
Task: [AB#7852](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7852)
> 7852: Added canned data for GetPrice

- src/NHSD.BuyingCatalogue.Database/PostDeployment/MigrateSolutionDetailToCatalogueItem.sql
- src/NHSD.BuyingCatalogue.Database/PostDeployment/PostDeployment.sql
- src/NHSD.BuyingCatalogue.Database/PreDeployment/MigrateSolutionDetailToCatalogueItem.sql
> Reorder certain DDL to avoid dependency issues

- GitVersion.yml
[AB#7824](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7824)
> add gitversion file

- src/NHSD.BuyingCatalogue.Database/PostDeployment/MigrateSolutionDetailToCatalogueItem.sql
- src/NHSD.BuyingCatalogue.Database/PreDeployment/PreDeployment.sql
> Prevent deployment failing when creating new DB

- src/NHSD.BuyingCatalogue.Database.Deployment/Dockerfile
- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertSolutions.sql
created prices for stock solutions
everything was tabbed into line on my machine, if it's all over the place let me know and i'll just remove it down to 1 space
[AB#7547](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7547)
> 7826: Select Price

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/PriceController.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/GetPriceBySolutionIdHandler.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET list of prices.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET single price.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Pricing/CataloguePriceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/PriceControllerTests.cs
Story: [AB#7826](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7826)
Task: [AB#8051](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8051)
> 7826: Price check for null

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/AdditionalServiceController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditonalServiceSolutionResult.cs
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8157](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8157)
> 5352: Canned data additional service

- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportAdditionalService.sql
- src/NHSD.BuyingCatalogue.Database/Tables/AdditionalService.sql
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/AdditionalServiceController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditonalServiceSolutionResult.cs
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8215](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8215)
> 5352: Additional Service Db & Canned data update

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertProvisioningTypes.sql
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/ProvisioningType.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET list of prices.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET single price.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Pricing/CataloguePriceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Domain/ProvisioningTypeTests.cs
[AB#8218](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8218)
[AB#8119](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8119)
> Changed provisioning types to match ordapi #8218

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/AdditionalServiceController.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/AdditionalService.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Mapping/SolutionAutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/AdditionalServiceReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetAdditionalServiceByAdditionalServiceId/AdditionalServiceDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetAdditionalServiceByAdditionalServiceId/GetAdditionalServiceByCatalogueItemIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/ServiceCollectionExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/IAdditionalService.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/IAdditionalServiceRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/IAdditionalServiceResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetAdditionalServiceBySolutionIdsQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Models/AdditionalServiceResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/AdditionalServiceRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/ServiceCollectionExtensions.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/AdditionalService/Get List of Additional Services.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/AdditionalService/AdditionalServiceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AdditionalServiceControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/AdditionalServiceDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/AdditionalServiceGetBySolutionIdsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionAutoMapperProfileTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/AdditionalServiceRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.Testing.Data/Entities/AdditionalServiceEntity.cs
- tests/NHSD.BuyingCatalogue.Testing.Data/EntityBuilders/AdditionalServiceEntityBuilder.cs
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8158](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8158)
> 5352: Additional Service GET

- src/NHSD.BuyingCatalogue.Database/NHSD.BuyingCatalogue.Database.sqlproj
- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertAdditionalServices.sql
- src/NHSD.BuyingCatalogue.Database/PostDeployment/PostDeployment.sql
Story [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task [AB#8169](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8169)
> 5352: Added additional services test data

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertAdditionalServices.sql
Story [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task [AB#8169](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8169)
> 5352:Review comments from tony

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/AdditionalServiceController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceListResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceModel.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceSolutionModel.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/AdditionalService/Get List of Additional Services.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/AdditionalService/AdditionalServiceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AdditionalServiceControllerTests.cs
Story: [AB#5352](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5352)
Task: [AB#8251](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8251)
> Feature/5352 Fix GET additional services endpoint

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/Suppliers/SuppliersController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/QueryModels/SupplierSearchQueryModel.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/SupplierReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSuppliersByName/GetSuppliersByNameHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/CatalogueItemType.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISupplierRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetSuppliersByNameQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SupplierRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Supplier/Supplier Search.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/AdditionalService/AdditionalServiceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Suppliers/SuppliersControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Persistence/SupplierReaderTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/GetSuppliersByNameTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SupplierRepositoryTests.cs
Bug: [AB#8252](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8252)
Task: [AB#8259](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8259)
> Fix duplicate supplier search results

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertSolutions.sql
changed currency code on test data to only GBP
other cides give error, Jos says only GBP valid so fixing test data
> 7405: Edit a single Catalogue Solution - Flat List Price - Variable (Patient numbers)

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/CatalogueItemsController.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/CatalogueItems/CatalogueItemReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetCatalogueItemById/ListCatalogueItemHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetCatalogueItemById/ListCatalogueItemQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/CatalogueItems/ICatalogueItemRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/CatalogueItemRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/CatalogueItems/Catalogue Item List.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/CatalogueItems/ListCatalogueItemSteps.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/StepArgumentTransformations.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Entities/CatalogueItemEntitySteps.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Support/ScenarioContextKeys.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/CatalogueItemsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Persistence/CatalogueItemReaderTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/CatalogueItems/ListCatalogueItemHandlerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/CatalogueItemRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/TestContext.cs
Story: [AB#7264](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7264)
Task: [AB#8348](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8348)
> 7264: Get catalogue items list

- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/AdditionalServiceController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/AdditionalService/AdditionalServiceModel.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/AdditionalService/Get List of Additional Services.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/AdditionalService/AdditionalServiceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AdditionalServiceControllerTests.cs
Story: [AB#7580](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7580)
Task: [AB#8525](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8525)
> Feature/7580 Rename additional service id to catalogue item id

- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/BrowserBased/SolutionConnectionAndResolution/Supplier Edit Solution Connection And Resolution.3599.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/ClientApplicationTypes/Supplier Edit Client Application Type.2726.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Features/Suppliers Edit Features Section.1828.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/ImplementationTimescales/Suppliers Edit Solution Implementation Timescales Section.3670.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Integrations/Suppliers Edit Solution Integrations Section.3667.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Roadmap/Suppliers Edit Solution Roadmap Section.3664.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/SolutionDescription/Suppliers Edit Solution Description Section.1843.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/SolutionList/No selection criteria browse.2053.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/UpdateSolution/Supplier Submitted for Moderation State Change.3012.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Entities/SolutionDetailEntitySteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionDetailRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionRepositoryTests.cs
Story: [AB#8870](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8870)
Task: [AB#7755](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7755)
> 8870: Review ignored tests

- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportSolution.sql
Story: [AB#9433](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9433)
Task: [AB#9435](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9435)
> 9435: Updated ImportSolution to use small hypen

- azure-pipelines.yml
Activity: [AB#9806](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9806)
Task: [AB#9808](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9808)
> Remove reference to development in condition

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
Activity: [AB#9953](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9953)
Task: [AB#9951](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9951)
> Add per virtual PC pricing unit

- src/NHSD.BuyingCatalogue.Database.PublishAll/PublishAll.dtsx
Activity: [AB#9971](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9971)
Task: [AB#9659](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9659)
> Add pricing data

- src/NHSD.BuyingCatalogue.Database/Functions/GetSupplierId.sql
- src/NHSD.BuyingCatalogue.Database/NHSD.BuyingCatalogue.Database.sqlproj
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportAdditionalService.sql
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportAssociatedService.sql
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportSolution.sql
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/PublishCatalogueItem.sql
- src/NHSD.BuyingCatalogue.Database/Types/AssociatedCatalogueItems.sql
- src/NHSD.BuyingCatalogue.Database/Types/SolutionCapability.sql
Adds a stored procedure for importing an associated service. Also tidied up existing import stored procedures to minimize statements executed under a transaction.
Activity: [AB#9953](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9953)
Task: [AB#9981](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9981)
> Add stored procedure to import associated service

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
- src/NHSD.BuyingCatalogue.Database/Tables/PricingUnit.sql
Activity: [AB#10015](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10015)
Task: [AB#10029](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10029)
> Add pricing units

- src/NHSD.BuyingCatalogue.Database.PublishAll/PublishAll.dtsx
Activity: [AB#10600](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10600)
Task: [AB#10633](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10633)
> Synchronize pricing units

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
- src/NHSD.BuyingCatalogue.Database/PreDeployment/PreDeployment.sql
- src/NHSD.BuyingCatalogue.Database/Tables/PricingUnit.sql
Activity: [AB#10640](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10640)
Task: [AB#10701](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10701)
> Update pricing unit description max length to 40

- src/NHSD.BuyingCatalogue.Database.PublishAll/PublishAll.dtsx
Activity: AB#10640
Task: AB#10748
> Update pricing unit description metadata

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertCapabilities.sql
- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertCapabilityCategories.sql
- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertEpics.sql
- src/NHSD.BuyingCatalogue.Database/Tables/Epic.sql
Story: [AB#10813](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10813)
Tasks: [AB#10843](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10843), [AB#10844](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10844)
> Add Covid-19 vaccination capabilities and epics

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertEpics.sql
Story: [AB#10813](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10813)
Task: [AB#10858](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/10858)
> Add epics for Covid-19 vax capability 47

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
Activity: [AB#11185](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11185)
Task: [AB#11188](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11188)
> Add 'concurrent clinical user' pricing unit

- .editorconfig
- NHSD.BuyingCatalogue.sln.DotSettings
- src/NHSD.BuyingCatalogue.Capabilities.API/NHSD.BuyingCatalogue.Capabilities.API.csproj
- src/NHSD.BuyingCatalogue.Capabilities.Application/NHSD.BuyingCatalogue.Capabilities.Application.csproj
- src/NHSD.BuyingCatalogue.Capabilities.Contracts/NHSD.BuyingCatalogue.Capabilities.Contracts.csproj
- src/NHSD.BuyingCatalogue.Capabilities.Persistence/NHSD.BuyingCatalogue.Capabilities.Persistence.csproj
- src/NHSD.BuyingCatalogue.Data/Infrastructure/DbConnectionFactory.cs
- src/NHSD.BuyingCatalogue.Data/Infrastructure/DbConnector.cs
- src/NHSD.BuyingCatalogue.Data/Infrastructure/IDbConnectionFactory.cs
- src/NHSD.BuyingCatalogue.Data/Infrastructure/IDbConnector.cs
- src/NHSD.BuyingCatalogue.Data/NHSD.BuyingCatalogue.Data.csproj
- src/NHSD.BuyingCatalogue.Database.Deployment/NHSD.BuyingCatalogue.Database.Deployment.csproj
- src/NHSD.BuyingCatalogue.Infrastructure/Enumerator.cs
- src/NHSD.BuyingCatalogue.Infrastructure/Exceptions/NotFoundException.cs
- src/NHSD.BuyingCatalogue.Infrastructure/NHSD.BuyingCatalogue.Infrastructure.csproj
- src/NHSD.BuyingCatalogue.Infrastructure/StringExtensions.cs
- src/NHSD.BuyingCatalogue.Infrastructure/ValueObject.cs
> Add StyleCop to infrastructure projects

- src/NHSD.BuyingCatalogue.SolutionLists.API/NHSD.BuyingCatalogue.SolutionLists.API.csproj
- src/NHSD.BuyingCatalogue.SolutionLists.API/SolutionListController.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/ListSolutionsFilterViewModel.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/ListSolutionsResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionCapabilityResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionSummaryResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionSupplierResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Domain/SolutionList.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Domain/SolutionListItem.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Domain/SolutionListItemCapability.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Domain/SolutionListItemSupplier.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Mapping/SolutionListAutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/NHSD.BuyingCatalogue.SolutionLists.Application.csproj
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Persistence/SolutionListReader.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/ListSolutionsHandler.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/ListSolutionsQuery.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/SolutionCapabilityDto.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/SolutionSummaryDto.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Queries/ListSolutions/SolutionSupplierDto.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/ISolutionCapability.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/ISolutionSummary.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/ISolutionSupplier.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/NHSD.BuyingCatalogue.SolutionLists.Contracts.csproj
- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/Persistence/ISolutionListRepository.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Persistence/NHSD.BuyingCatalogue.SolutionLists.Persistence.csproj
- src/NHSD.BuyingCatalogue.SolutionLists.Persistence/Repositories/SolutionListRepository.cs
> Add StyleCop to solutions lists projects

- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/ClaimedCapability.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Contact.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Hosting.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/NativeDesktop/NativeDesktopMemoryAndStorage.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/CataloguePriceFlat.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/CataloguePriceTier.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/CataloguePriceType.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/ProvisioningType.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Pricing/TimeUnit.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Solution.cs
> Fix StyleCop violations up to SA1201 in Solution App project Domain

- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/AdditionalServiceReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/ContactDetailsReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/ImplementationTimescalesReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/IntegrationsReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/PriceReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/RoadMapReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/SolutionCapabilitiesUpdater.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/SolutionReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/SolutionVerifier.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/Suppliers/SolutionSupplierPartialUpdater.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/Suppliers/SolutionSupplierUpdater.cs
> Fix StyleCop violations up to SA1201 in Solutions App project Persistence

- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetAdditionalServiceByAdditionalServiceId/GetAdditionalServiceByCatalogueItemIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetCatalogueItemById/GetCatalogueItemByIdQueryHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/ClientApplicationDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/GetClientApplicationBySolutionIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetContactDetailBySolutionId/GetContactDetailBySolutionIdQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetHostingBySolutionId/GetHostingBySolutionIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetHostingBySolutionId/HostingDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetImplementationTimescalesBySolutionId/GetImplementationTimescalesBySolutionIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetIntegrationsBySolutionId/GetIntegrationsBySolutionIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingByPriceId/GetPricingByPriceIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/GetPricesHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetRoadMapBySolutionId/GetRoadMapBySolutionIdHandler.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSolutionById/SolutionDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSupplierBySolutionId/GetSupplierBySolutionIdHandler.cs
> Fix StyleCop violations up to SA1201 in Queries

- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/BrowserBased/UpdateSolutionConnectivityAndResolution/UpdateSolutionConnectivityAndResolutionCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/NativeMobile/UpdateSolutionMobileMemoryAndStorage/UpdateSolutionMobileMemoryStorageCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/NativeMobile/UpdateSolutionMobileOperatingSystems/UpdateSolutionMobileOperatingSystemsCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateImplementationTimescales/UpdateImplementationTimescalesCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/ClaimedCapabilityEpic.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/MobileConnectionDetails.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/MobileOperatingSystems.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/OnPremise.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/PrivateCloud.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/Epics/ClaimedEpicResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/Suppliers/UpdateSupplierRequest.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/UpdateCapabilityRequest.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetAdditionalServiceByAdditionalServiceId/AdditionalServiceDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/MobileConnectionDetailsDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/MobileOperatingSystemsDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/MobileThirdPartyDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/NativeDesktopMemoryAndStorageDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/NativeDesktopThirdPartyDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetContactDetailBySolutionId/ContactDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetHostingBySolutionId/PrivateCloudDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetIntegrationsBySolutionId/IntegrationsDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/CataloguePriceDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/PricingUnitDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/TieredPriceDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetPricingBySolutionId/TimeUnitDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetRoadMapBySolutionId/RoadMapDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSolutionById/ClaimedCapabilityDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSolutionById/ClaimedCapabilityEpicDto.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetSolutionById/OnPremiseDto.cs
> Fix element spacing in Solutions App project

- src/NHSD.BuyingCatalogue.SolutionLists.Contracts/ISolutionSummary.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/UpdateSolutionSummaryViewModel.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/BrowserBased/UpdateSolutionBrowsersSupported/UpdateSolutionBrowsersSupportedCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/UpdateSolutionClientApplicationTypes/UpdateSolutionClientApplicationTypesCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/SubmitForReview/SubmitSolutionForReviewCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/SubmitForReview/SubmitSolutionForReviewValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/SubmitForReview/ValidationError.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSolutionContactDetails/UpdateSolutionContactDetailsCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSolutionFeatures/UpdateSolutionFeaturesCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSolutionSummary/UpdateSolutionSummaryCommand.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Solution.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Mapping/SolutionAutoMapperProfile.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/ClientApplicationPartialUpdater.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/HostingPartialUpdater.cs
> Fix XML docs in Solutions App project

- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/SolutionRoadmapUpdater.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/UpdateRoadmapRequest.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/BrowserBased/IUpdateBrowserBasedPluginsData.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/IUpdateSolutionFeatures.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/IUpdateSolutionSummary.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/IClientApplication.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/IContact.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/IHosting.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/ISolution.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/IAdditionalServiceRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/IMarketingContactRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISolutionCapabilityRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISolutionDetailRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISolutionEpicRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISolutionRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/ISupplierRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Persistence/IUpdateRoadmapRequest.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Pricing/ICataloguePrice.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/PublishedStatus.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetClientApplicationBySolutionIdQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetHostingBySolutionIdQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetSolutionByIdQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Queries/GetSupplierBySolutionIdQuery.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/SupplierStatus.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionDetailRepository.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateRoadmapTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionDetailRepositoryTests.cs
> Fix StyleCop errors excluding order and spacing in Solutions Contracts project

- src/NHSD.BuyingCatalogue.Capabilities.Persistence/Repositories/CapabilityRepository.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Persistence/Repositories/SolutionListRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/NHSD.BuyingCatalogue.Solutions.Persistence.csproj
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/AdditionalServiceRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/DocumentRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/EpicRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/MarketingContactRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/PriceRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionCapabilityRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionDetailRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionEpicRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionEpicStatusRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionRepository.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SupplierRepository.cs
> Fix element order and tidy SQL consts

- src/NHSD.BuyingCatalogue.API/Extensions/TrimmingConverter.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/Filters/CustomExceptionFilter.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/Filters/SerilogLoggingActionFilter.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/Logging/LoggingBehaviour.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/Logging/SerilogRequestLoggingOptions.cs
- src/NHSD.BuyingCatalogue.API/Infrastructure/Settings.cs
- src/NHSD.BuyingCatalogue.API/NHSD.BuyingCatalogue.API.csproj
- src/NHSD.BuyingCatalogue.API/Program.cs
- src/NHSD.BuyingCatalogue.API/Startup.cs
- src/NHSD.BuyingCatalogue.Contracts/NHSD.BuyingCatalogue.Contracts.csproj
- src/NHSD.BuyingCatalogue.Infrastructure/CollectionExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ClientApplicationBrowserBasedExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ClientApplicationNativeMobileExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/ClientApplications/BrowserBased/BrowsersSupportedSectionAnswers.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/NativeMobile/UpdateSolutionMobileMemoryAndStorage/UpdateSolutionMobileMemoryStorageExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/Hostings/IUpdateHybridHostingTypeData.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/Hostings/IUpdateOnPremiseData.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/Hostings/IUpdatePrivateCloudData.cs
- src/NHSD.BuyingCatalogue.Solutions.Contracts/Commands/Hostings/IUpdatePublicCloudData.cs
- tests/NHSD.BuyingCatalogue.API.UnitTests/TrimmingConverterTests.cs
> Add StyleCop and fix errors in API and contracts projects

- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AuthorityDashboard/SolutionAuthorityDashboardResultTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AuthorityDashboard/SolutionAuthorityDashboardSectionsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AuthorityDashboard/SolutionsControllerGetAuthorityDashboardTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/AdditionalServiceDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/CatalogueItemDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/FlatCataloguePriceDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/GetCatalogueItemResultBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/PriceUnitDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Builders/TieredCataloguePriceDtoBuilder.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/NativeMobile/NativeMobileControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionDescriptionControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetDashboardTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPreviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPublicTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerSubmitForReviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerTests.cs
> Fix some style violations in solutions test projects

- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/AuthorityDashboard/SolutionAuthorityDashboardResultTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/BrowserAdditionalInformationControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/BrowserBasedControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/BrowserHardwareRequirementsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/BrowserMobileFirstControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/BrowserSupportedControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/ConnectivityAndResolutionControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/BrowserBased/PluginsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionDescriptionControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetDashboardTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPreviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPublicTests.cs
> Fix some style violations in solutions API tests project

- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ContactDetailsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NHSD.BuyingCatalogue.Solutions.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetDashboardTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPublicTests.cs
> Fix remaining solutions tests style issues

- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/CatalogueItems/ListCatalogueItemHandlerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateBrowserAdditionalInformationTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateBrowserHardwareRequirementsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateBrowserMobileFirstTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateBrowsersSupportedTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateConnectivityAndResolutionTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdatePluginsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/ClientApplicationTestsBase.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/GetClientApplicationBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/SolutionUpdateNativeDesktopConnectivityDetailsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/SolutionUpdateNativeDesktopOperatingSystemsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/SolutionUpdateNativeDesktopThirdPartyTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/UpdateNativeDesktopAdditionalInformationTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/UpdateNativeDesktopHardwareRequirementsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeDesktop/UpdateNativeDesktopMemoryAndStorageTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateMemoryAndStorageTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateMobileConnectionDetailsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateMobileOperatingSystemsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateMobileThirdPartyTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateNativeMobileAdditionalInformationTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateNativeMobileFirstTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/NativeMobile/SolutionUpdateNativeMobileHardwareRequirementsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/SolutionUpdateClientApplicationTypesTests.cs
> Fix StyleCop violations in solution app tests

- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Domain/ProvisioningTypeTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Domain/SolutionTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Domain/SupplierStatusTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/GetHostingBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/HostingTestsBase.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/UpdateHybridHostingTypeTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/UpdateOnPremiseTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/UpdatePrivateCloudTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Hostings/UpdatePublicCloudTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Pricing/GetPricingByPriceIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Pricing/GetPricingTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/GetSupplierByIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/GetSupplierBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/GetSuppliersByNameTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Suppliers/UpdateSolutionSupplierTests.cs
> Fix style issues in solutions app tests

- NHSD.BuyingCatalogue.sln.DotSettings
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/AdditionalServiceGetBySolutionIdsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ContactDetailsGetBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/GetImplementationTimescalesBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/GetIntegrationsBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/GetRoadMapBySolutionIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionAutoMapperProfileTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionGetByIdTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionSubmitForReviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateContactDetailsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateFeaturesTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateImplementationTimescalesTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateIntegrationsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateRoadmapTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/SolutionUpdateSummaryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/UpdateClaimedEpicsHandlerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/UpdateSolutionCapabilitiesTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ValidationErrorTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ValidationResultTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Tools/EnumerableStringExtensions.cs
> Fix remaining style issues in solutions app tests

- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/NativeDesktop/NativeDesktopThirdPartyControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/AdditionalServiceRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/CatalogueItemRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/DatabaseTestsSetup.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/MarketingContactsRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/Models/CapabilityDetails.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/PriceRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionCapabilityRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionDetailRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionEpicRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SolutionRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/SupplierRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.UnitTests/DocumentRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.UnitTests/NHSD.BuyingCatalogue.Solutions.Persistence.UnitTests.csproj
> Fix style violations in solutions test projects

- tests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests/CapabilitiesControllerTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/CapabilityAutoMapperProfileTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/CapabilityListTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/CapabilityRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/DatabaseTestsSetup.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/TestContext.cs
> Fix style issues in capabilities tests

- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/SolutionListControllerTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/SolutionListAutoMapperProfileTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/SolutionListTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/DatabaseTestsSetup.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/SolutionListRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/TestContext.cs
Task: [AB#11094](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11094), [AB#11095](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11095)
> Fix style issues in solutions lists tests

- tests/NHSD.BuyingCatalogue.Data.Tests/NHSD.BuyingCatalogue.Data.Tests.csproj
- tests/NHSD.BuyingCatalogue.Data.Tests/ServiceCollectionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/EnumeratorTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/ExceptionExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/NHSD.BuyingCatalogue.Infrastructure.Tests.csproj
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/NotFoundExceptionTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/StringExtensionsTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/ValueObjectTests.cs
> Fix style issues in infrastructure tests

- tests/NHSD.BuyingCatalogue.API.UnitTests/Logging/SerilogRequestLoggingOptionsTests.cs
- tests/NHSD.BuyingCatalogue.API.UnitTests/NHSD.BuyingCatalogue.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.API.UnitTests/SettingsTests.cs
- tests/NHSD.BuyingCatalogue.API.UnitTests/TrimmingConverterTests.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/CapabilityRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Persistence.DatabaseTests/DatabaseTestsSetup.cs
- tests/NHSD.BuyingCatalogue.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ClientApplications/NativeMobile/MobileOperatingSystemsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/ContactDetailsControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/PriceControllerTests.cs
> Fix style issues in test code

- src/NHSD.BuyingCatalogue.Capabilities.Application/Domain/Capability.cs
- src/NHSD.BuyingCatalogue.Capabilities.Persistence/Models/CapabilityListResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/ClientApplication/NativeMobile/MobileOperatingSystemsController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/ClientApplications/NativeMobile/UpdateNativeMobileFirstViewModel.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Hostings/UpdateHybridHostingTypeViewModel.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/ContactDetailsSection.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/UpdateSolutionContactViewModelConverter.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/BrowserBased/UpdateSolutionConnectivityAndResolution/UpdateSolutionConnectivityAndResolutionValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/NativeMobile/UpdateSolutionMobileMemoryAndStorage/UpdateSolutionMobileMemoryStorageValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/ClientApplications/NativeMobile/UpdateSolutionMobileOperatingSystems/UpdateSolutionMobileOperatingSystemsValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSolutionContactDetails/UpdateSolutionContactDetailsExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/Validation/MaxLengthResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/Validation/RequiredResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/ClientApplication.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/MobileMemoryAndStorage.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/MobileThirdParty.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/NativeDesktop/NativeDesktopThirdParty.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Queries/GetClientApplicationBySolutionId/PluginsDto.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/ContactDetails/ContactDetailsUpdateSteps.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Entities/CapabilityEntitySteps.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Entities/DatabaseSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/ClientApplications/BrowserBased/SolutionUpdateConnectivityAndResolutionTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/TestContext.cs
- tests/NHSD.BuyingCatalogue.Testing.Data/Entities/MarketingContactEntity.cs
- tests/NHSD.BuyingCatalogue.Testing.Data/EntityBuilders/MarketingContactEntityBuilder.cs
> Seal all unsealed classes

- src/NHSD.BuyingCatalogue.API/NHSD.BuyingCatalogue.API.csproj
- src/NHSD.BuyingCatalogue.Capabilities.API/NHSD.BuyingCatalogue.Capabilities.API.csproj
- src/NHSD.BuyingCatalogue.Infrastructure/NHSD.BuyingCatalogue.Infrastructure.csproj
- src/NHSD.BuyingCatalogue.SolutionLists.API/NHSD.BuyingCatalogue.SolutionLists.API.csproj
- src/NHSD.BuyingCatalogue.Solutions.API/NHSD.BuyingCatalogue.Solutions.API.csproj
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/NHSD.BuyingCatalogue.API.IntegrationTests.csproj
- tests/NHSD.BuyingCatalogue.API.UnitTests/NHSD.BuyingCatalogue.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests/NHSD.BuyingCatalogue.Capabilities.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests/NHSD.BuyingCatalogue.Capabilities.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Data.Tests/NHSD.BuyingCatalogue.Data.Tests.csproj
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/EnumeratorTests.cs
- tests/NHSD.BuyingCatalogue.Infrastructure.Tests/NHSD.BuyingCatalogue.Infrastructure.Tests.csproj
- tests/NHSD.BuyingCatalogue.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests/NHSD.BuyingCatalogue.SolutionLists.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests/NHSD.BuyingCatalogue.SolutionLists.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests/NHSD.BuyingCatalogue.SolutionLists.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/NHSD.BuyingCatalogue.Solutions.API.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Application.UnitTests/Solutions/Domain/SupplierStatusTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests/NHSD.BuyingCatalogue.Solutions.Persistence.DatabaseTests.csproj
- tests/NHSD.BuyingCatalogue.Solutions.Persistence.UnitTests/NHSD.BuyingCatalogue.Solutions.Persistence.UnitTests.csproj
> Update dependencies and fix null ref warnings in tests

- src/NHSD.BuyingCatalogue.Infrastructure/CollectionExtensions.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/ViewModels/SolutionSummaryResult.cs
- src/NHSD.BuyingCatalogue.SolutionLists.Application/Domain/SolutionList.cs
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/PriceController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Hosting/GetHybridHostingTypeResult.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/ClientApplications/BrowserBased/BrowsersSupportedSectionAnswers.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/ClientApplications/BrowserBased/PluginOrExtensionsSectionAnswers.cs
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/SubmitSolutionForReviewResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/Execution/ExecutorExtensions.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/SubmitForReview/SubmitSolutionForReviewValidator.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/SubmitForReview/ValidationResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateClaimedEpics/UpdateClaimedEpicsExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/UpdateSolutionContactDetails/UpdateSolutionContactDetailsExecutor.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Commands/Validation/ClaimedEpicsVerifier.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Domain/Solution.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/CatalogueItems/CatalogueItemReader.cs
- src/NHSD.BuyingCatalogue.Solutions.Application/Persistence/Epics/SolutionEpicsUpdater.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SupplierRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/IntegrationSetupFixture.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/CatalogueItems/ListCatalogueItemSteps.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Pricing/CataloguePriceSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Hosting/HybridHostingTypeControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Hosting/OnPremiseHostingControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Hosting/PrivateCloudHostingControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/Hosting/PublicCloudHostingControllerTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPreviewTests.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerGetPublicTests.cs
> Fix null checks and lazy lambda params

- src/NHSD.BuyingCatalogue.Database.PublishAll/PublishAll.dtsx
> Update metadata (varchar to nvarchar)

- src/NHSD.BuyingCatalogue.API/Infrastructure/Filters/CustomExceptionFilter.cs
- src/NHSD.BuyingCatalogue.Capabilities.API/CapabilitiesController.cs
- src/NHSD.BuyingCatalogue.SolutionLists.API/SolutionListController.cs
- src/NHSD.BuyingCatalogue.Solutions.API/Controllers/ClientApplication/BrowserBased/BrowserAdditionalInformationController.cs
> Use media type name constants

- .editorconfig
- NHSD.BuyingCatalogue.sln.DotSettings
> Ensure style settings are consistent

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertEpics.sql
Activity: [AB#11665](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11665)
Task: [AB#11619](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11619)
> MERGE epics instead of INSERT

- src/NHSD.BuyingCatalogue.Database/Tables/CataloguePrice.sql
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET list of prices.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Price/GET single price.feature
Story: [AB#11143](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11143)
Task: [AB#12049](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12049)
> Add support for prices with up to 4 decimal places

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertFrameworks.sql
- src/NHSD.BuyingCatalogue.Database/Tables/Framework.sql
Story [AB#11258](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11258)
Task [AB#12934](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12934)
Task [AB#12935](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12935)
> Add ShortName column into Framework Table

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertEpics.sql
Bug [AB#9765](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9765)
Task [AB#13154](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13154)
> Update Epics data

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
Story [AB#13180](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13180)
Task [AB#13201](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13201)
> Add Pricing Unit

- charts/bapi/templates/ingress.yaml
Task: [AB#11823](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11823)
Activity: [AB#13202](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13202)
> Ingress configuration updated to v1

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertSolutions.sql
Story: [AB#11203](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11203)
Task: [AB#13455](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13455)
> Fix test data for DFOCVC solutions

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertSolutions.sql
Story: [AB#11203](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11203)
Task: [AB#13465](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13465)
Tidied up the insert prices SQL too.
> Move test DFOCVC solutions to a different supplier

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
Story [AB#13180](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13180)
Task [AB#13505](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13505)
> Add new Pricing unit

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
- src/NHSD.BuyingCatalogue.Solutions.API/ViewModels/Solution/GetSolutionResult.cs
- src/NHSD.BuyingCatalogue.Solutions.Persistence/Repositories/SolutionRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Solution/Solution Get.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Common/CommonSteps.cs
- tests/NHSD.BuyingCatalogue.Solutions.API.UnitTests/SolutionsControllerTests.cs
Story [AB#13379](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13379)
Task [AB#13558](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13558)
> Solution query update to retrieve IsFoundation

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertPricingUnits.sql
- src/NHSD.BuyingCatalogue.Database/Tables/PricingUnit.sql
Story [AB#13140](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13140)
Task [AB#13664](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13664)
> Revert price description to 40 characters in BAPI

- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertAdditionalServices.sql
- src/NHSD.BuyingCatalogue.Database/PostDeployment/InsertSolutions.sql
Bug: [AB#13476](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13476)
Task: [AB#13748](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13748)
> Fix test per patient pricing data

- src/NHSD.BuyingCatalogue.Database/Functions/GetSupplierId.sql
- src/NHSD.BuyingCatalogue.Database/NHSD.BuyingCatalogue.Database.sqlproj
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportAdditionalService.sql
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportAssociatedService.sql
- src/NHSD.BuyingCatalogue.Database/Stored Procedures/ImportSolution.sql
- src/NHSD.BuyingCatalogue.Database/Types/AdditionalServices.sql
- src/NHSD.BuyingCatalogue.Database/Types/AssociatedCatalogueItems.sql
- src/NHSD.BuyingCatalogue.Database/Types/AssociatedServices.sql
- src/NHSD.BuyingCatalogue.Database/Types/SolutionCapability.sql
- src/NHSD.BuyingCatalogue.Database/Types/Solutions.sql
Activity: [AB#12841](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12841)
Task: [AB#12842](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12842)
**Example usage**
```sql
-- Solutions
DECLARE @newSolutions AS import.Solutions;
INSERT INTO @newSolutions(Id, [Name], IsFoundation, FrameworkId)
VALUES
('100000-999', 'Chris 1', 0, 'NHSDGP001'),
('100000-998', 'Chris 2', 0, 'NHSDGP001');
DECLARE @solutionCapabilities AS import.SolutionCapability;
INSERT INTO @solutionCapabilities(SolutionId, CapabilityRef)
VALUES
('100000-999', 'C1'),
('100000-999', 'C2'),
('100000-998', 'C1');
EXEC import.ImportSolution @newSolutions, @solutionCapabilities;
-- Additional services
DECLARE @newAdditionalServices AS …
```
> Update ImportSolution to support multiple solutions

- src/NHSD.BuyingCatalogue.Capabilities.Persistence/Repositories/CapabilityRepository.cs
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Features/Capability/CapabilityList.feature
- tests/NHSD.BuyingCatalogue.API.IntegrationTests/Steps/Entities/CapabilityEntitySteps.cs
- tests/NHSD.BuyingCatalogue.Capabilities.Persistence.DatabaseTests/CapabilityRepositoryTests.cs
- tests/NHSD.BuyingCatalogue.Testing.Data/EntityBuilders/CapabilityEntityBuilder.cs
Update list capabilities endpoint to return only GP IT capabilities
Story: [AB#14164](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14164)
Task: [AB#14246](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14246)
> Remove DFOCVC capabilities from Capability Selector

- src/NHSD.BuyingCatalogue.Database.PublishAll/PublishAll.dtsx
Activity: [AB#14239](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14239)
Task: [AB#14288](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14288)
> Include supplier and supplier contact details
